# --- WEB SETTINGS (JSP) ---
spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp

# --- SERVER ---
server.port=8080

# --- DEBUG LOGGING ---
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.context=DEBUG
